### ISSUE TITLE
Practica02_InterfazgraficaVisualStudio_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-equipo-topicos-avanzados#2]
[Practica02_InterfazGraficaVisual_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US.zip](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-equipo-topicos-avanzados/files/8085035/Practica02_InterfazGraficaVisual_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US.zip)

**Comment by JudithReynaCS** [comment]
Dentro de la carpeta se encuentra el PDF

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
Y la calificación..????

**Comment by SANDRAVELASCO** [comment]
Calificación: 20
